/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AudioCore: typeof import('./components/AudioCore.vue')['default']
    CodeMirror: typeof import('./components/CodeMirror.vue')['default']
    CrowFeather: typeof import('./components/CrowFeather.vue')['default']
    CustomCursor: typeof import('./components/CustomCursor.vue')['default']
    DownloadModal: typeof import('./components/DownloadModal.vue')['default']
    GothicBorder: typeof import('./components/GothicBorder.vue')['default']
    GothicCorner: typeof import('./components/GothicCorner.vue')['default']
    InteractiveGrid: typeof import('./components/InteractiveGrid.vue')['default']
    IntroView: typeof import('./components/IntroView.vue')['default']
    LoadingScreen: typeof import('./components/LoadingScreen.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCheckbox: typeof import('naive-ui')['NCheckbox']
    NColorPicker: typeof import('naive-ui')['NColorPicker']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDivider: typeof import('naive-ui')['NDivider']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModalProvider: typeof import('naive-ui')['NModalProvider']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NSelect: typeof import('naive-ui')['NSelect']
    NSpin: typeof import('naive-ui')['NSpin']
    NTooltip: typeof import('naive-ui')['NTooltip']
    OptionView: typeof import('./components/OptionView.vue')['default']
    OrnateCorner: typeof import('./components/OrnateCorner.vue')['default']
    ParallaxScene: typeof import('./components/ParallaxScene.vue')['default']
    PreviewBbs: typeof import('./components/previews/preview-bbs.vue')['default']
    PreviewBbsItem: typeof import('./components/previews/preview-bbs-item.vue')['default']
    PreviewBbsPineapple: typeof import('./components/previews/preview-bbs-pineapple.vue')['default']
    PreviewBbsPineappleItem: typeof import('./components/previews/preview-bbs-pineapple-item.vue')['default']
    PreviewMain: typeof import('./components/previews/preview-main.vue')['default']
    PreviewMainItem: typeof import('./components/previews/preview-main-item.vue')['default']
    PreviewTableTr: typeof import('./components/previews/preview-table-tr.vue')['default']
    PreviewTrg: typeof import('./components/previews/preview-trg.vue')['default']
    PreviewTrgItem: typeof import('./components/previews/preview-trg-item.vue')['default']
    RetroButton: typeof import('./components/RetroButton.vue')['default']
    SteampunkBackground: typeof import('./components/SteampunkBackground.vue')['default']
    TypewriterText: typeof import('./components/TypewriterText.vue')['default']
  }
}
